# estagio 1 - base  
FROM mcr.microsoft.com/dotnet/aspnet:5.0 as base
WORKDIR /app
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80 

# estagio 2 - publish
FROM mcr.microsoft.com/dotnet/sdk:5.0-focal as publish
WORKDIR /app
COPY *.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o dist

#estagio 3 - final
FROM base as final
WORKDIR /dist
COPY --from=publish /app/dist .
ENTRYPOINT  [ "dotnet","MvcComDocker.dll" ]