# construção da imagem de sdk do .NET 5 com alias de  “build-env”
FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build-env

#Estamos definindo que a pasta que estarei trabalhando é a “app” (mesmo que não tenha, ele irá criar!)
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

COPY . ./

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0

WORKDIR /app

COPY --from=build-env /app/out .

ENV ASPNETCORE_URLS=http://+:80  

EXPOSE 80

ENTRYPOINT  [ "dotnet","MvcComDocker.dll" ]